#!/bin/bash

REAL_USER="${SUDO_USER:-$USER}"
REAL_HOME="$(getent passwd "$REAL_USER" | cut -d: -f6)"
REAL_HOME="${REAL_HOME:-$HOME}"

BACKUP_IP="${BACKUP_IP:-}"
BACKUP_USER="${BACKUP_USER:-backup}"
TEAM_SUBNET="${TEAM_SUBNET:-192.168.0.0/24}"
USERS_FILE="${USERS_FILE:-$REAL_HOME/users.txt}"
SCORING_KEY="${SCORING_KEY:-}"
LOG="${LOG:-$REAL_HOME/hardening_log.txt}"
BACKUP_DIR="${BACKUP_DIR:-/.backup}"
RECENT_MINUTES="${RECENT_MINUTES:-60}"

TEAM_NUMBER="${TEAM_NUMBER:-}"
INT_DOMAIN="${INT_DOMAIN:-}"
EXT_DOMAIN="${EXT_DOMAIN:-}"

INT_NS_HOST="${INT_NS_HOST:-ns1}"
EXT_NS_HOST="${EXT_NS_HOST:-ns1}"
INT_WWW_HOST="${INT_WWW_HOST:-www}"
INT_DB_HOST="${INT_DB_HOST:-db}"
EXT_WWW_HOST="${EXT_WWW_HOST:-www}"
EXT_SHELL_HOST="${EXT_SHELL_HOST:-shell}"
EXT_FILES_HOST="${EXT_FILES_HOST:-files}"

INT_NS_IP="${INT_NS_IP:-}"
INT_WWW_IP="${INT_WWW_IP:-}"
INT_DB_IP="${INT_DB_IP:-}"

EXT_NS_IP="${EXT_NS_IP:-}"
EXT_WWW_IP="${EXT_WWW_IP:-}"
EXT_SHELL_IP="${EXT_SHELL_IP:-}"
EXT_FILES_IP="${EXT_FILES_IP:-}"

INT_REVERSE_ZONE="${INT_REVERSE_ZONE:-}"
EXT_REVERSE_ZONE="${EXT_REVERSE_ZONE:-}"

INT_NS_PTR="${INT_NS_PTR:-}"
INT_WWW_PTR="${INT_WWW_PTR:-}"
INT_DB_PTR="${INT_DB_PTR:-}"

EXT_NS_PTR="${EXT_NS_PTR:-}"
EXT_WWW_PTR="${EXT_WWW_PTR:-}"
EXT_SHELL_PTR="${EXT_SHELL_PTR:-}"
EXT_FILES_PTR="${EXT_FILES_PTR:-}"

POSTGRES_PORT="${POSTGRES_PORT:-5432}"
POSTGRES_LISTEN_ADDRESSES="${POSTGRES_LISTEN_ADDRESSES:-*}"
POSTGRES_ALLOWED_SUBNET="${POSTGRES_ALLOWED_SUBNET:-$TEAM_SUBNET}"
BACKUP_FOLDERS="${BACKUP_FOLDERS:-web dns db shell smb misc}"
